### ISSUE TITLE
lighthouse integration 2.1.0 - form_factor: desktop - runtime error

### ISSUE THREAD

**Issue by dllegru** [DataDog/integrations-extras#1325] opened 2022-05-27 11:13 UTC
**Output of the [info page](https://docs.datadoghq.com/integrations/lighthouse/)**

```
    lighthouse (2.1.0)
    ------------------
      Instance ID: lighthouse:BetFox Production:d6e887c897baf5dd [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/lighthouse.d/conf.yaml
      Total Runs: 2
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 902ms
      Last Execution Date : 2022-05-27 11:02:34 UTC (1653649354000)
      Last Successful Execution Date : Never
      Error: ('', 'Runtime error encountered: Screen emulation mobile setting (true) does not match formFactor setting (desktop). See https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md\nError: Screen emulation mobile setting (true) does not match formFactor setting (desktop). See https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md\n    at Object.assertValidSettings (/usr/lib/node_modules/lighthouse/lighthouse-core/fraggle-rock/config/validation.js:224:13)\n    at resolveSettings (/usr/lib/node_modules/lighthouse/lighthouse-core/config/config-helpers.js:323:14)\n    at new Config (/usr/lib/node_modules/lighthouse/lighthouse-core/config/config.js:195:22)\n    at generateConfig (/usr/lib/node_modules/lighthouse/lighthouse-core/index.js:66:10)\n    at lighthouse (/usr/lib/node_modules/lighthouse/lighthouse-core/index.js:44:18)\n    at runLighthouse (file:///usr/lib/node_modules/lighthouse/lighthouse-cli/run.js:252:14)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n', 1)
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 1120, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/lighthouse/lighthouse.py", line 47, in check
          raise CheckException(json_string, error_message, exit_code)
      datadog_checks.base.errors.CheckException: ('', 'Runtime error encountered: Screen emulation mobile setting (true) does not match formFactor setting (desktop). See https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md\nError: Screen emulation mobile setting (true) does not match formFactor setting (desktop). See https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md\n    at Object.assertValidSettings (/usr/lib/node_modules/lighthouse/lighthouse-core/fraggle-rock/config/validation.js:224:13)\n    at resolveSettings (/usr/lib/node_modules/lighthouse/lighthouse-core/config/config-helpers.js:323:14)\n    at new Config (/usr/lib/node_modules/lighthouse/lighthouse-core/config/config.js:195:22)\n    at generateConfig (/usr/lib/node_modules/lighthouse/lighthouse-core/index.js:66:10)\n    at lighthouse (/usr/lib/node_modules/lighthouse/lighthouse-core/index.js:44:18)\n    at runLighthouse (file:///usr/lib/node_modules/lighthouse/lighthouse-cli/run.js:252:14)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n', 1)
```

**Steps to reproduce the issue:**
Using new optional parameter `form_factor:` available in `v2.1.0` integration:
- value: `mobile` works fine.
- value: `desktop` throws following runtime error:
```
Error: ('', 'Runtime error encountered: Screen emulation mobile setting (true) does not match formFactor setting (desktop). See https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md\nError: Screen emulation mobile setting (true) does not match formFactor setting (desktop). See https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md\n    at Object.assertValidSettings (/usr/lib/node_modules/lighthouse/lighthouse-core/fraggle-rock/config/validation.js:224:13)\n    at resolveSettings (/usr/lib/node_modules/lighthouse/lighthouse-core/config/config-helpers.js:323:14)\n    at new Config (/usr/lib/node_modules/lighthouse/lighthouse-core/config/config.js:195:22)\n    at generateConfig (/usr/lib/node_modules/lighthouse/lighthouse-core/index.js:66:10)\n    at lighthouse (/usr/lib/node_modules/lighthouse/lighthouse-core/index.js:44:18)\n    at runLighthouse (file:///usr/lib/node_modules/lighthouse/lighthouse-cli/run.js:252:14)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n', 1)
```

**Additional information you deem important (e.g. issue happens only occasionally):**
I guess the following [parameter](https://github.com/GoogleChrome/lighthouse/issues/12246#issuecomment-799739034) `--no-screenEmulation.mobile` has to be appended in the `lighthouse` cmd when `desktop` is set as `form_factor`

**Comment by hithwen** [comment] 2022-05-30 11:10
Hallo @baerbradford, this seems related to [your PR](https://github.com/DataDog/integrations-extras/pull/1123). Would you be able to have a look?

**Comment by baerbradford** [comment] 2022-06-08 21:46
Hey @hithwen , I don't quite have the time to try to reproduce this and test it but I think @dllegru's suggestion about including `--no-screenEmulation.mobile` definitely looks like it is worth a shot.

The relevant place to change this would be here:

https://github.com/DataDog/integrations-extras/blob/33ebbd6d991d32b39a6e03f0b5c2dbacb6043859/lighthouse/datadog_checks/lighthouse/lighthouse.py#L37-L38

We could just add an additional condition here to append the extra parameter. Would look something like this:

```
if form_factor:
    cmd.append("--form-factor=" + form_factor)
    if form_factor == "desktop":
        cmd.append("--no-screenEmulation.mobile")
```

@dllegru You might also double check what version of Lighthouse you're using and whether upgrading helps. I see the issue describes version 7, but they are up to 9.x now. When I was extending this integration, I don't seem to recall having any trouble collecting metrics for `desktop` and we're using version 9.

**Comment by fanny-jiang** [comment] 2022-08-11 17:46
Hi @dllegru, have you had a chance to try upgrading Lighthouse as @baerbradford suggested? Please let us know if upgrading resolves the issue for you.

**Comment by HoriaA** [comment] 2023-01-17 09:52
Hey @fanny-jiang! I have this same issue and found a similar solution to that described above. I opened https://github.com/DataDog/integrations-extras/pull/1729 with the fix I found, could you help reviewing it?

**Comment by baerbradford** [comment] 2023-01-17 14:59
Nice work @HoriaA. Appreciate you taking the time to reproduce it and make a PR for the fix.

**Comment by HoriaA** [comment] 2023-01-19 14:15
Version 2.1.1 fixed this for me, @dllegru can you try it as well?

**Comment by dllegru** [comment] 2023-02-08 11:56
Hi @HoriaA, @fanny-jiang , will test in the next coming days and confirm it, thanks!

**Comment by yzhan289** [comment] 2023-04-18 18:28
Hi @dllegru , just want to check back. Does the fix resolve this issue?

**Comment by alopezz** [comment] 2023-07-10 10:31
I'm going to close this since it seems solved and there hasn't been activity in a while.

**Closed by alopezz** 2023-07-10 10:31 UTC
